<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="round_bot">

  <!-- Robot properties -->
  <xacro:property name="body_radius" value="0.3"/>
  <xacro:property name="head_radius" value="0.15"/>

  <!-- Materials -->
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <!-- BASE FOOTPRINT (ground contact, z=0) -->
  <link name="base_footprint"/>

  <!-- BASE LINK (sphere center, lifted so bottom touches ground) -->
  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${body_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link"/>

  <!-- BODY SPHERE (red) -->
  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body"/>
    <origin xyz="0 0 0"/>
  </joint>

  <link name="body">
    <visual>
      <geometry>
        <sphere radius="${body_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${body_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- HEAD SPHERE (blue, sits on top of red body) -->
  <joint name="head_joint" type="fixed">
    <parent link="body"/>
    <child link="head"/>
    <!-- place it so the bottom of the blue sphere touches the top of the red sphere -->
    <origin xyz="0 0 ${body_radius + head_radius}" rpy="0 0 0"/>
  </joint>

  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- Yellow forward marker -->
  <joint name="forward_marker_joint" type="fixed">
    <parent link="base_link"/>
    <child link="forward_marker"/>
    <origin xyz="${body_radius} 0 0" rpy="0 0 0"/> <!-- placed in front along x-axis -->
  </joint>

  <link name="forward_marker">
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>
  </link>

</robot>
